language: "zh"

pipeline:
  - name: "MitieNLP"
    model: "examples/xiaoasheng/data/total_word_feature_extractor_zh.dat"
  - name: "JiebaTokenizer"
  - name: "MitieEntityExtractor"
  - name: "EntitySynonymMapper"
  - name: "RegexFeaturizer"
  - name: "MitieFeaturizer"
  - name: "SklearnIntentClassifier"

policies:
  - name: TEDPolicy
    max_history: 5
    epochs: 200
    batch_size: 50
    max_training_samples: 300
  - name: MemoizationPolicy
  - name: RulePolicy