language: "zh"

pipeline:
  - name: "MitieNLP"
    model: "examples/xiaoasheng/data/total_word_feature_extractor_zh.dat"
  - name: "JiebaTokenizer"
  - name: "RegexEntityExtractor"
  - name: "MitieEntityExtractor"
  - name: "EntitySynonymMapper"
  - name: "RegexFeaturizer"
  - name: "MitieFeaturizer"
  - name: "SklearnIntentClassifier"
  - name: "FallbackClassifier"
    threshold: 0.25

policies:
  - name: TEDPolicy
    max_history: 5
    epochs: 200
    batch_size: 50
    max_training_samples: 300
  - name: MemoizationPolicy
    max_history: 5
  - name: RulePolicy
    core_fallback_threshold: 0.2
    core_fallback_action_name: action_default_fallback
    enable_fallback_prediction: true
    restrict_rules: true
    check_for_contradictions: true